version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy-prod:
    docker:
      # specify the version you desire here (you might not want node)
      - image: circleci/node:7.10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d3:bc:5d:0a:fb:10:0e:b7:ca:46:a0:4b:be:b6:91:6a"
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP -p $PORT sh ./deploy_neymo_front.sh

  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
#           - run: yarn test
workflows:
  build-and-deploy:
    jobs:
      - deploy-prod
      - build-and-test